
services:

  task-service:
    build: ./backend
    ports:
      - "8085:8085"

  analytics-service:
    build: ./analytics-service
    ports:
      - "8086:8086"
    environment:
      TASK_SERVICE_URL: http://task-service:8085/tasks
    depends_on:
      - task-service

  notification-service:
    build: ./notification-service
    ports:
      - "8087:8087"
    environment:
      TASK_SERVICE_URL: http://task-service:8085/tasks
    depends_on:
      - task-service

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - task-service
      - analytics-service
      - notification-service

  prometheus:
    image: prom/prometheus:v2.55.1
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - task-service
      - analytics-service
      - notification-service

  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
