
services:

  task-service:
    build: ./backend
    ports:
      - "8085:8085"

  analytics-service:
    build: ./analytics-service
    ports:
      - "8086:8086"
    environment:
      TASK_SERVICE_URL: http://task-service:8085/tasks
    depends_on:
      - task-service

  notification-service:
    build: ./notification-service
    ports:
      - "8087:8087"
    environment:
      TASK_SERVICE_URL: http://task-service:8085/tasks
    depends_on:
      - task-service

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - task-service
      - analytics-service
      - notification-service

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
